server:
  port: 8081

spring:
  application:
    name: hmdp

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.88.99:3306/hmdp?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
  redis:
    host: 192.168.88.99
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
  rabbitmq:
    host: 192.168.88.99
    username: guest
    password: guest
    virtual-host: /
    port: 5672
    listener:
      simple:
        # 消费者最小数量
        concurrency: 10
        # 消费这最大数量
        max-concurrency: 10
        # 限制消费者每次只处理一条消息, 处理完再继续下一条消息
        prefetch: 1
        # 启动时是否默认启动容器, 默认为true
        auto-startup: true
        # 被拒绝时重新进入队列
        default-requeue-rejected: true

    template:
      retry:
        # 发布重试, 默认为false
        enabled: true
        # 重试时间, 默认1000ms
        initial-interval: 1000ms
        # 重试最大次数, 默认三次
        max-attempts: 3
        # 最大间隔时间, 默认10000ms
        max-interval: 10000ms
        # 重试的间隔系数, eg: 系数为2, 第一次等待10s, 则第二次等待20s, 第三次等待40s
        multiplier: 1

mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug