---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Jo.
--- DateTime: 2024/8/12 9:55
--- redisson源码
--- 释放锁:
local key = KEYS[1]; --
local threadId = ARGV[1];
local releaseTime = ARGV[2];
-- 判断锁是否是被自己所持有
if (redis.call('HEXISTS', key, threadId) == 0) then
    return nil; -- 如果不是自己的, 则直接返回
end
-- 是自己的, 重入次数减一
local count = redis.call('HINCRBY', key, thread, -1);
-- 判断是否重入次数是否为0
if (count > 0) then
    -- 大于0则说明不能释放锁, 重置有效期然后返回
    redis.call('EXPIRE', key, releaseTime);
    return nil;
else -- 重入次数为0, 则释放锁
    redis.call('DEL', key);
    return nil;
end